In [89]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt 
import warnings

warnings.filterwarnings('ignore')

In [90]:
titles = pd.read_csv('../data/titles.csv')
credits = pd.read_csv('../data/credits.csv')
titles
credits

,person_id,id,name,character,role
0,3180,tm82169,Sylvester Stallone,"Robert ""Rocky"" Balboa",ACTOR
1,7748,tm82169,Talia Shire,"Adrianna ""Adrian"" Pennino",ACTOR
2,7749,tm82169,Burt Young,Paulie Pennino,ACTOR
3,7750,tm82169,Carl Weathers,Apollo Creed,ACTOR
4,7751,tm82169,Burgess Meredith,Mickey Goldmill,ACTOR
...,...,...,...,...,...
81350,449518,tm1072700,Kayode Olaiya,Uncle Adio,ACTOR
81351,2722717,tm1072700,Tolu Osaile,Sade,ACTOR
81352,2722797,tm1072700,Eniola Oyetola,Officer Meks,ACTOR
81353,866314,tm1072700,Tope Tedela,Officer Jack,ACTOR
81354,1807691,tm1072700,Taiwo Egunjobi,NaN,DIRECTOR

In [91]:
titles.shape

(6137, 15)

In [92]:
credits

,person_id,id,name,character,role
0,3180,tm82169,Sylvester Stallone,"Robert ""Rocky"" Balboa",ACTOR
1,7748,tm82169,Talia Shire,"Adrianna ""Adrian"" Pennino",ACTOR
2,7749,tm82169,Burt Young,Paulie Pennino,ACTOR
3,7750,tm82169,Carl Weathers,Apollo Creed,ACTOR
4,7751,tm82169,Burgess Meredith,Mickey Goldmill,ACTOR
...,...,...,...,...,...
81350,449518,tm1072700,Kayode Olaiya,Uncle Adio,ACTOR
81351,2722717,tm1072700,Tolu Osaile,Sade,ACTOR
81352,2722797,tm1072700,Eniola Oyetola,Officer Meks,ACTOR
81353,866314,tm1072700,Tope Tedela,Officer Jack,ACTOR
81354,1807691,tm1072700,Taiwo Egunjobi,NaN,DIRECTOR

In [93]:
titles

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.601,NaN
1,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782
2,tm17823,Grease,MOVIE,Australian good girl Sandy and greaser Danny f...,1978,PG,110,"['romance', 'comedy']",['US'],NaN,tt0077631,7.2,283316.0,33.160,7.406
3,tm191099,The Sting,MOVIE,A novice con man teams up with an acknowledged...,1973,PG,129,"['crime', 'drama', 'comedy', 'music']",['US'],NaN,tt0070735,8.3,266738.0,24.616,8.020
4,tm69975,Rocky II,MOVIE,After Rocky goes the distance with champ Apoll...,1979,PG,119,"['drama', 'sport']",['US'],NaN,tt0079817,7.3,216307.0,75.699,7.246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,tm1303784,عبود في البيت,MOVIE,Two young boys must work together to stop robb...,2023,NaN,81,"['family', 'comedy']",['KW'],NaN,NaN,NaN,NaN,3.351,2.000
6133,tm1260999,Sweetie,MOVIE,"‘Theatre is my life,’ Yıldız Kenter admits in ...",2023,NaN,120,['documentation'],['TR'],NaN,tt26349328,7.9,209.0,2.450,7.200
6134,tm1310286,Sommore: Queen Chandelier,MOVIE,This Queen of Comedy shines as she takes the s...,2023,NaN,69,['comedy'],['US'],NaN,tt21033382,6.1,91.0,1.960,NaN
6135,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000
6136,tm561709,Going to Heaven,MOVIE,"A story about young boy sultan, 11 years old l...",2023,NaN,90,['family'],['AE'],NaN,tt4623222,7.0,40.0,NaN,NaN

In [94]:
df = titles.merge(credits, on="id", how="left")

In [95]:
df

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.601,NaN,NaN,NaN,NaN,NaN
1,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782,3180.0,Sylvester Stallone,"Robert ""Rocky"" Balboa",ACTOR
2,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782,7748.0,Talia Shire,"Adrianna ""Adrian"" Pennino",ACTOR
3,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782,7749.0,Burt Young,Paulie Pennino,ACTOR
4,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782,7750.0,Carl Weathers,Apollo Creed,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81699,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000,2722717.0,Tolu Osaile,Sade,ACTOR
81700,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000,2722797.0,Eniola Oyetola,Officer Meks,ACTOR
81701,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000,866314.0,Tope Tedela,Officer Jack,ACTOR
81702,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000,1807691.0,Taiwo Egunjobi,NaN,DIRECTOR
81703,tm561709,Going to Heaven,MOVIE,"A story about young boy sultan, 11 years old l...",2023,NaN,90,['family'],['AE'],NaN,tt4623222,7.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
df.shape

(81704, 19)

In [97]:
df.columns

Index(['id', 'title', 'type', 'description', 'release_year',
       'age_certification', 'runtime', 'genres', 'production_countries',
       'seasons', 'imdb_id', 'imdb_score', 'imdb_votes', 'tmdb_popularity',
       'tmdb_score', 'person_id', 'name', 'character', 'role'],
      dtype='object')

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81704 entries, 0 to 81703
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    81704 non-null  object
 1   title                 81704 non-null  object
 2   type                  81704 non-null  object
 3   description           81650 non-null  object
 4   release_year          81704 non-null  int64
 5   age_certification     47683 non-null  object
 6   runtime               81704 non-null  int64
 7   genres                81704 non-null  object
 8   production_countries  81704 non-null  object
 9   seasons               17032 non-null  float64
 10  imdb_id               78418 non-null  object
 11  imdb_score            77938 non-null  float64
 12  imdb_votes            77863 non-null  float64
 13  tmdb_popularity       81615 non-null  float64
 14  tmdb_score            80664 non-null  float64
 15  person_id             81355 non-null  float64
 16  name                  81355 non-null  object
 17  character             70532 non-null  object
 18  role                  81355 non-null  object
dtypes: float64(6), int64(2), object(11)
memory usage: 11.8+ MB

In [99]:
df.isnull().sum()

id                          0
title                       0
type                        0
description                54
release_year                0
age_certification       34021
runtime                     0
genres                      0
production_countries        0
seasons                 64672
imdb_id                  3286
imdb_score               3766
imdb_votes               3841
tmdb_popularity            89
tmdb_score               1040
person_id                 349
name                      349
character               11172
role                      349
dtype: int64

In [100]:
df.duplicated(subset='id').sum()

np.int64(75567)

In [101]:
#Shows duplicated row
df[df.duplicated(subset='id', keep= False)].sort_values('id')

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
77877,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,76618.0,Marlon Boess,Pankraz,ACTOR
77872,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,251702.0,Luna Wedler,Maxi,ACTOR
77874,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,589580.0,Milan Peschel,Alex,ACTOR
77875,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,191901.0,Edin Hasanović,Ante,ACTOR
77876,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,237433.0,Anna Fialová,Jitka,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7622,ts98353,DreamWorks Spooky Stories,SHOW,A collection of animated tales includes shrek'...,2009,NaN,26,"['animation', 'family']",['US'],1.0,tt6958564,6.2,27.0,0.880,NaN,3691.0,Mike Myers,NaN,ACTOR
1398,ts987,Danger Mouse,SHOW,"Danger Mouse, the world's greatest secret agen...",1981,TV-Y,14,"['animation', 'comedy', 'family', 'scifi', 'ac...",['GB'],10.0,tt0081848,7.4,3678.0,6.517,7.2,18355.0,Edward Kelsey,Colonel K / Baron Greenback (voice),ACTOR
1397,ts987,Danger Mouse,SHOW,"Danger Mouse, the world's greatest secret agen...",1981,TV-Y,14,"['animation', 'comedy', 'family', 'scifi', 'ac...",['GB'],10.0,tt0081848,7.4,3678.0,6.517,7.2,99172.0,Terry Scott,Penfold (voice),ACTOR
1396,ts987,Danger Mouse,SHOW,"Danger Mouse, the world's greatest secret agen...",1981,TV-Y,14,"['animation', 'comedy', 'family', 'scifi', 'ac...",['GB'],10.0,tt0081848,7.4,3678.0,6.517,7.2,43162.0,David Jason,Danger Mouse / Narrator (voice),ACTOR
1399,ts987,Danger Mouse,SHOW,"Danger Mouse, the world's greatest secret agen...",1981,TV-Y,14,"['animation', 'comedy', 'family', 'scifi', 'ac...",['GB'],10.0,tt0081848,7.4,3678.0,6.517,7.2,99173.0,Brian Trueman,Stiletto (voice),ACTOR

In [102]:
#Keeping the real dataset unchanged
df_work = df.copy()

In [103]:
df_work

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.601,NaN,NaN,NaN,NaN,NaN
1,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782,3180.0,Sylvester Stallone,"Robert ""Rocky"" Balboa",ACTOR
2,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782,7748.0,Talia Shire,"Adrianna ""Adrian"" Pennino",ACTOR
3,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782,7749.0,Burt Young,Paulie Pennino,ACTOR
4,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782,7750.0,Carl Weathers,Apollo Creed,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81699,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000,2722717.0,Tolu Osaile,Sade,ACTOR
81700,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000,2722797.0,Eniola Oyetola,Officer Meks,ACTOR
81701,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000,866314.0,Tope Tedela,Officer Jack,ACTOR
81702,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000,1807691.0,Taiwo Egunjobi,NaN,DIRECTOR
81703,tm561709,Going to Heaven,MOVIE,"A story about young boy sultan, 11 years old l...",2023,NaN,90,['family'],['AE'],NaN,tt4623222,7.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
df[df.duplicated(subset='id', keep=False)].sort_values('id')

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
77877,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,76618.0,Marlon Boess,Pankraz,ACTOR
77872,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,251702.0,Luna Wedler,Maxi,ACTOR
77874,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,589580.0,Milan Peschel,Alex,ACTOR
77875,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,191901.0,Edin Hasanović,Ante,ACTOR
77876,tm1000037,Je suis Karl,MOVIE,After most of her family is murdered in a terr...,2021,R,126,"['drama', 'thriller', 'european', 'romance']","['CZ', 'DE']",NaN,tt9205538,5.5,1283.0,4.870,5.4,237433.0,Anna Fialová,Jitka,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7622,ts98353,DreamWorks Spooky Stories,SHOW,A collection of animated tales includes shrek'...,2009,NaN,26,"['animation', 'family']",['US'],1.0,tt6958564,6.2,27.0,0.880,NaN,3691.0,Mike Myers,NaN,ACTOR
1398,ts987,Danger Mouse,SHOW,"Danger Mouse, the world's greatest secret agen...",1981,TV-Y,14,"['animation', 'comedy', 'family', 'scifi', 'ac...",['GB'],10.0,tt0081848,7.4,3678.0,6.517,7.2,18355.0,Edward Kelsey,Colonel K / Baron Greenback (voice),ACTOR
1397,ts987,Danger Mouse,SHOW,"Danger Mouse, the world's greatest secret agen...",1981,TV-Y,14,"['animation', 'comedy', 'family', 'scifi', 'ac...",['GB'],10.0,tt0081848,7.4,3678.0,6.517,7.2,99172.0,Terry Scott,Penfold (voice),ACTOR
1396,ts987,Danger Mouse,SHOW,"Danger Mouse, the world's greatest secret agen...",1981,TV-Y,14,"['animation', 'comedy', 'family', 'scifi', 'ac...",['GB'],10.0,tt0081848,7.4,3678.0,6.517,7.2,43162.0,David Jason,Danger Mouse / Narrator (voice),ACTOR
1399,ts987,Danger Mouse,SHOW,"Danger Mouse, the world's greatest secret agen...",1981,TV-Y,14,"['animation', 'comedy', 'family', 'scifi', 'ac...",['GB'],10.0,tt0081848,7.4,3678.0,6.517,7.2,99173.0,Brian Trueman,Stiletto (voice),ACTOR

In [105]:
df_work = df_work.drop_duplicates(subset='id', keep='first')

In [106]:
df_work.duplicated().sum()

np.int64(0)

In [107]:
df_work[df_work.duplicated(subset='id', keep=False)].sort_values('id')

Empty DataFrame
Columns: [id, title, type, description, release_year, age_certification, runtime, genres, production_countries, seasons, imdb_id, imdb_score, imdb_votes, tmdb_popularity, tmdb_score, person_id, name, character, role]
Index: []

In [108]:
df_work.shape

(6137, 19)

In [109]:
#Drop unnecessary columns 
df_work = df_work.drop(columns=[
    'description',
    'imdb_id', 
    'character',
    'person_id', 
    'seasons', 
])

In [110]:
df_work

,id,title,type,release_year,age_certification,runtime,genres,production_countries,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,ts300399,Five Came Back: The Reference Films,SHOW,1945,TV-MA,51,['documentation'],['US'],NaN,NaN,0.601,NaN,NaN,NaN
1,tm82169,Rocky,MOVIE,1976,PG,119,"['drama', 'sport']",['US'],8.1,588100.0,106.361,7.782,Sylvester Stallone,ACTOR
51,tm17823,Grease,MOVIE,1978,PG,110,"['romance', 'comedy']",['US'],7.2,283316.0,33.160,7.406,John Travolta,ACTOR
99,tm191099,The Sting,MOVIE,1973,PG,129,"['crime', 'drama', 'comedy', 'music']",['US'],8.3,266738.0,24.616,8.020,Paul Newman,ACTOR
142,tm69975,Rocky II,MOVIE,1979,PG,119,"['drama', 'sport']",['US'],7.3,216307.0,75.699,7.246,Sylvester Stallone,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81649,tm1303784,عبود في البيت,MOVIE,2023,NaN,81,"['family', 'comedy']",['KW'],NaN,NaN,3.351,2.000,Bader Al Atwan,ACTOR
81655,tm1260999,Sweetie,MOVIE,2023,NaN,120,['documentation'],['TR'],7.9,209.0,2.450,7.200,Yıldız Kenter,ACTOR
81685,tm1310286,Sommore: Queen Chandelier,MOVIE,2023,NaN,69,['comedy'],['US'],6.1,91.0,1.960,NaN,Sommore,ACTOR
81687,tm1072700,All Na Vibes,MOVIE,2023,NaN,80,['drama'],['NG'],5.2,18.0,1.357,4.000,Adeola Layade Azaria,ACTOR
81703,tm561709,Going to Heaven,MOVIE,2023,NaN,90,['family'],['AE'],7.0,40.0,NaN,NaN,NaN,NaN

In [111]:
df_work.drop(columns=['id'], inplace=True)

In [112]:
df_work

,title,type,release_year,age_certification,runtime,genres,production_countries,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,51,['documentation'],['US'],NaN,NaN,0.601,NaN,NaN,NaN
1,Rocky,MOVIE,1976,PG,119,"['drama', 'sport']",['US'],8.1,588100.0,106.361,7.782,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,PG,110,"['romance', 'comedy']",['US'],7.2,283316.0,33.160,7.406,John Travolta,ACTOR
99,The Sting,MOVIE,1973,PG,129,"['crime', 'drama', 'comedy', 'music']",['US'],8.3,266738.0,24.616,8.020,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,PG,119,"['drama', 'sport']",['US'],7.3,216307.0,75.699,7.246,Sylvester Stallone,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,MOVIE,2023,NaN,81,"['family', 'comedy']",['KW'],NaN,NaN,3.351,2.000,Bader Al Atwan,ACTOR
81655,Sweetie,MOVIE,2023,NaN,120,['documentation'],['TR'],7.9,209.0,2.450,7.200,Yıldız Kenter,ACTOR
81685,Sommore: Queen Chandelier,MOVIE,2023,NaN,69,['comedy'],['US'],6.1,91.0,1.960,NaN,Sommore,ACTOR
81687,All Na Vibes,MOVIE,2023,NaN,80,['drama'],['NG'],5.2,18.0,1.357,4.000,Adeola Layade Azaria,ACTOR
81703,Going to Heaven,MOVIE,2023,NaN,90,['family'],['AE'],7.0,40.0,NaN,NaN,NaN,NaN

In [113]:
df_work.head()

,title,type,release_year,age_certification,runtime,genres,production_countries,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,51,['documentation'],['US'],NaN,NaN,0.601,NaN,NaN,NaN
1,Rocky,MOVIE,1976,PG,119,"['drama', 'sport']",['US'],8.1,588100.0,106.361,7.782,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,PG,110,"['romance', 'comedy']",['US'],7.2,283316.0,33.160,7.406,John Travolta,ACTOR
99,The Sting,MOVIE,1973,PG,129,"['crime', 'drama', 'comedy', 'music']",['US'],8.3,266738.0,24.616,8.020,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,PG,119,"['drama', 'sport']",['US'],7.3,216307.0,75.699,7.246,Sylvester Stallone,ACTOR

In [114]:
df_work.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6137 entries, 0 to 81703
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 6137 non-null   object
 1   type                  6137 non-null   object
 2   release_year          6137 non-null   int64
 3   age_certification     3394 non-null   object
 4   runtime               6137 non-null   int64
 5   genres                6137 non-null   object
 6   production_countries  6137 non-null   object
 7   imdb_score            5669 non-null   float64
 8   imdb_votes            5653 non-null   float64
 9   tmdb_popularity       6061 non-null   float64
 10  tmdb_score            5885 non-null   float64
 11  name                  5788 non-null   object
 12  role                  5788 non-null   object
dtypes: float64(4), int64(2), object(7)
memory usage: 671.2+ KB

In [115]:
df_work.drop(columns=['age_certification'], inplace=True)

In [116]:
df_work

,title,type,release_year,runtime,genres,production_countries,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,51,['documentation'],['US'],NaN,NaN,0.601,NaN,NaN,NaN
1,Rocky,MOVIE,1976,119,"['drama', 'sport']",['US'],8.1,588100.0,106.361,7.782,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,110,"['romance', 'comedy']",['US'],7.2,283316.0,33.160,7.406,John Travolta,ACTOR
99,The Sting,MOVIE,1973,129,"['crime', 'drama', 'comedy', 'music']",['US'],8.3,266738.0,24.616,8.020,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,119,"['drama', 'sport']",['US'],7.3,216307.0,75.699,7.246,Sylvester Stallone,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,MOVIE,2023,81,"['family', 'comedy']",['KW'],NaN,NaN,3.351,2.000,Bader Al Atwan,ACTOR
81655,Sweetie,MOVIE,2023,120,['documentation'],['TR'],7.9,209.0,2.450,7.200,Yıldız Kenter,ACTOR
81685,Sommore: Queen Chandelier,MOVIE,2023,69,['comedy'],['US'],6.1,91.0,1.960,NaN,Sommore,ACTOR
81687,All Na Vibes,MOVIE,2023,80,['drama'],['NG'],5.2,18.0,1.357,4.000,Adeola Layade Azaria,ACTOR
81703,Going to Heaven,MOVIE,2023,90,['family'],['AE'],7.0,40.0,NaN,NaN,NaN,NaN

In [117]:
df_work.head()

,title,type,release_year,runtime,genres,production_countries,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,51,['documentation'],['US'],NaN,NaN,0.601,NaN,NaN,NaN
1,Rocky,MOVIE,1976,119,"['drama', 'sport']",['US'],8.1,588100.0,106.361,7.782,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,110,"['romance', 'comedy']",['US'],7.2,283316.0,33.160,7.406,John Travolta,ACTOR
99,The Sting,MOVIE,1973,129,"['crime', 'drama', 'comedy', 'music']",['US'],8.3,266738.0,24.616,8.020,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,119,"['drama', 'sport']",['US'],7.3,216307.0,75.699,7.246,Sylvester Stallone,ACTOR

In [118]:
df_work.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6137 entries, 0 to 81703
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 6137 non-null   object
 1   type                  6137 non-null   object
 2   release_year          6137 non-null   int64
 3   runtime               6137 non-null   int64
 4   genres                6137 non-null   object
 5   production_countries  6137 non-null   object
 6   imdb_score            5669 non-null   float64
 7   imdb_votes            5653 non-null   float64
 8   tmdb_popularity       6061 non-null   float64
 9   tmdb_score            5885 non-null   float64
 10  name                  5788 non-null   object
 11  role                  5788 non-null   object
dtypes: float64(4), int64(2), object(6)
memory usage: 623.3+ KB

In [119]:
df_work.isnull().sum()

title                     0
type                      0
release_year              0
runtime                   0
genres                    0
production_countries      0
imdb_score              468
imdb_votes              484
tmdb_popularity          76
tmdb_score              252
name                    349
role                    349
dtype: int64

In [120]:
#Filling the NaN
columns = ['imdb_score', 'imdb_votes', 'tmdb_popularity', 'tmdb_score']

for col in columns: 
    df_work[col] = df_work[col].fillna(df_work[col].mean())

In [121]:
df_work

,title,type,release_year,runtime,genres,production_countries,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,51,['documentation'],['US'],6.540942,21150.290819,0.601000,6.633194,NaN,NaN
1,Rocky,MOVIE,1976,119,"['drama', 'sport']",['US'],8.100000,588100.000000,106.361000,7.782000,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,110,"['romance', 'comedy']",['US'],7.200000,283316.000000,33.160000,7.406000,John Travolta,ACTOR
99,The Sting,MOVIE,1973,129,"['crime', 'drama', 'comedy', 'music']",['US'],8.300000,266738.000000,24.616000,8.020000,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,119,"['drama', 'sport']",['US'],7.300000,216307.000000,75.699000,7.246000,Sylvester Stallone,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,MOVIE,2023,81,"['family', 'comedy']",['KW'],6.540942,21150.290819,3.351000,2.000000,Bader Al Atwan,ACTOR
81655,Sweetie,MOVIE,2023,120,['documentation'],['TR'],7.900000,209.000000,2.450000,7.200000,Yıldız Kenter,ACTOR
81685,Sommore: Queen Chandelier,MOVIE,2023,69,['comedy'],['US'],6.100000,91.000000,1.960000,6.633194,Sommore,ACTOR
81687,All Na Vibes,MOVIE,2023,80,['drama'],['NG'],5.200000,18.000000,1.357000,4.000000,Adeola Layade Azaria,ACTOR
81703,Going to Heaven,MOVIE,2023,90,['family'],['AE'],7.000000,40.000000,19.267196,6.633194,NaN,NaN

In [122]:
df_work[columns].isna().sum()

imdb_score         0
imdb_votes         0
tmdb_popularity    0
tmdb_score         0
dtype: int64

In [123]:
(df_work[columns] == 0).sum()

imdb_score         0
imdb_votes         0
tmdb_popularity    0
tmdb_score         0
dtype: int64

In [124]:
df_work.head()

,title,type,release_year,runtime,genres,production_countries,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,51,['documentation'],['US'],6.540942,21150.290819,0.601,6.633194,NaN,NaN
1,Rocky,MOVIE,1976,119,"['drama', 'sport']",['US'],8.100000,588100.000000,106.361,7.782000,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,110,"['romance', 'comedy']",['US'],7.200000,283316.000000,33.160,7.406000,John Travolta,ACTOR
99,The Sting,MOVIE,1973,129,"['crime', 'drama', 'comedy', 'music']",['US'],8.300000,266738.000000,24.616,8.020000,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,119,"['drama', 'sport']",['US'],7.300000,216307.000000,75.699,7.246000,Sylvester Stallone,ACTOR

In [125]:
df_work.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6137 entries, 0 to 81703
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 6137 non-null   object
 1   type                  6137 non-null   object
 2   release_year          6137 non-null   int64
 3   runtime               6137 non-null   int64
 4   genres                6137 non-null   object
 5   production_countries  6137 non-null   object
 6   imdb_score            6137 non-null   float64
 7   imdb_votes            6137 non-null   float64
 8   tmdb_popularity       6137 non-null   float64
 9   tmdb_score            6137 non-null   float64
 10  name                  5788 non-null   object
 11  role                  5788 non-null   object
dtypes: float64(4), int64(2), object(6)
memory usage: 623.3+ KB

In [126]:
df_work

,title,type,release_year,runtime,genres,production_countries,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,51,['documentation'],['US'],6.540942,21150.290819,0.601000,6.633194,NaN,NaN
1,Rocky,MOVIE,1976,119,"['drama', 'sport']",['US'],8.100000,588100.000000,106.361000,7.782000,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,110,"['romance', 'comedy']",['US'],7.200000,283316.000000,33.160000,7.406000,John Travolta,ACTOR
99,The Sting,MOVIE,1973,129,"['crime', 'drama', 'comedy', 'music']",['US'],8.300000,266738.000000,24.616000,8.020000,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,119,"['drama', 'sport']",['US'],7.300000,216307.000000,75.699000,7.246000,Sylvester Stallone,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,MOVIE,2023,81,"['family', 'comedy']",['KW'],6.540942,21150.290819,3.351000,2.000000,Bader Al Atwan,ACTOR
81655,Sweetie,MOVIE,2023,120,['documentation'],['TR'],7.900000,209.000000,2.450000,7.200000,Yıldız Kenter,ACTOR
81685,Sommore: Queen Chandelier,MOVIE,2023,69,['comedy'],['US'],6.100000,91.000000,1.960000,6.633194,Sommore,ACTOR
81687,All Na Vibes,MOVIE,2023,80,['drama'],['NG'],5.200000,18.000000,1.357000,4.000000,Adeola Layade Azaria,ACTOR
81703,Going to Heaven,MOVIE,2023,90,['family'],['AE'],7.000000,40.000000,19.267196,6.633194,NaN,NaN

In [127]:
df_work['genres'] = df_work['genres'].str.extract(r"'([^']+)'")

In [128]:
df_work['genres']

0        documentation
1                drama
51             romance
99               crime
142              drama
             ...
81649           family
81655    documentation
81685           comedy
81687            drama
81703           family
Name: genres, Length: 6137, dtype: object

In [130]:
df_work.rename(columns={'genres': 'main_genre'}, inplace=True)

In [131]:
df_work

,title,type,release_year,runtime,main_genre,production_countries,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,51,documentation,['US'],6.540942,21150.290819,0.601000,6.633194,NaN,NaN
1,Rocky,MOVIE,1976,119,drama,['US'],8.100000,588100.000000,106.361000,7.782000,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,110,romance,['US'],7.200000,283316.000000,33.160000,7.406000,John Travolta,ACTOR
99,The Sting,MOVIE,1973,129,crime,['US'],8.300000,266738.000000,24.616000,8.020000,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,119,drama,['US'],7.300000,216307.000000,75.699000,7.246000,Sylvester Stallone,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,MOVIE,2023,81,family,['KW'],6.540942,21150.290819,3.351000,2.000000,Bader Al Atwan,ACTOR
81655,Sweetie,MOVIE,2023,120,documentation,['TR'],7.900000,209.000000,2.450000,7.200000,Yıldız Kenter,ACTOR
81685,Sommore: Queen Chandelier,MOVIE,2023,69,comedy,['US'],6.100000,91.000000,1.960000,6.633194,Sommore,ACTOR
81687,All Na Vibes,MOVIE,2023,80,drama,['NG'],5.200000,18.000000,1.357000,4.000000,Adeola Layade Azaria,ACTOR
81703,Going to Heaven,MOVIE,2023,90,family,['AE'],7.000000,40.000000,19.267196,6.633194,NaN,NaN

In [132]:
df_work['production_countries'] = df_work['production_countries'].str.extract(r"'([^']+)'")

In [133]:
df_work.rename(columns={'production_countries': 'lead_production_country'}, inplace=True)

In [134]:
df_work

,title,type,release_year,runtime,main_genre,lead_production_country,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,51,documentation,US,6.540942,21150.290819,0.601000,6.633194,NaN,NaN
1,Rocky,MOVIE,1976,119,drama,US,8.100000,588100.000000,106.361000,7.782000,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,110,romance,US,7.200000,283316.000000,33.160000,7.406000,John Travolta,ACTOR
99,The Sting,MOVIE,1973,129,crime,US,8.300000,266738.000000,24.616000,8.020000,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,119,drama,US,7.300000,216307.000000,75.699000,7.246000,Sylvester Stallone,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,MOVIE,2023,81,family,KW,6.540942,21150.290819,3.351000,2.000000,Bader Al Atwan,ACTOR
81655,Sweetie,MOVIE,2023,120,documentation,TR,7.900000,209.000000,2.450000,7.200000,Yıldız Kenter,ACTOR
81685,Sommore: Queen Chandelier,MOVIE,2023,69,comedy,US,6.100000,91.000000,1.960000,6.633194,Sommore,ACTOR
81687,All Na Vibes,MOVIE,2023,80,drama,NG,5.200000,18.000000,1.357000,4.000000,Adeola Layade Azaria,ACTOR
81703,Going to Heaven,MOVIE,2023,90,family,AE,7.000000,40.000000,19.267196,6.633194,NaN,NaN

In [135]:
df_work.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6137 entries, 0 to 81703
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   title                    6137 non-null   object
 1   type                     6137 non-null   object
 2   release_year             6137 non-null   int64
 3   runtime                  6137 non-null   int64
 4   main_genre               6080 non-null   object
 5   lead_production_country  5961 non-null   object
 6   imdb_score               6137 non-null   float64
 7   imdb_votes               6137 non-null   float64
 8   tmdb_popularity          6137 non-null   float64
 9   tmdb_score               6137 non-null   float64
 10  name                     5788 non-null   object
 11  role                     5788 non-null   object
dtypes: float64(4), int64(2), object(6)
memory usage: 623.3+ KB

In [136]:
df_work.isnull().sum()

title                        0
type                         0
release_year                 0
runtime                      0
main_genre                  57
lead_production_country    176
imdb_score                   0
imdb_votes                   0
tmdb_popularity              0
tmdb_score                   0
name                       349
role                       349
dtype: int64

In [140]:
#Filling categoriccal column with the most frequent value
df_work['main_genre'] = df_work['main_genre'].fillna(df_work['main_genre'].mode()[0])
df_work['lead_production_country'] = df_work['lead_production_country'].fillna(df_work['lead_production_country'].mode([0]))

In [141]:
#Filling cast informantion with a placeholder
df_work['name'] = df_work['name'].fillna("Unknown")
df_work['role'] = df_work['role'].fillna("Unknown")

In [142]:
df_work

,title,type,release_year,runtime,main_genre,lead_production_country,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,1945,51,documentation,US,6.540942,21150.290819,0.601000,6.633194,Unknown,Unknown
1,Rocky,MOVIE,1976,119,drama,US,8.100000,588100.000000,106.361000,7.782000,Sylvester Stallone,ACTOR
51,Grease,MOVIE,1978,110,romance,US,7.200000,283316.000000,33.160000,7.406000,John Travolta,ACTOR
99,The Sting,MOVIE,1973,129,crime,US,8.300000,266738.000000,24.616000,8.020000,Paul Newman,ACTOR
142,Rocky II,MOVIE,1979,119,drama,US,7.300000,216307.000000,75.699000,7.246000,Sylvester Stallone,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,MOVIE,2023,81,family,KW,6.540942,21150.290819,3.351000,2.000000,Bader Al Atwan,ACTOR
81655,Sweetie,MOVIE,2023,120,documentation,TR,7.900000,209.000000,2.450000,7.200000,Yıldız Kenter,ACTOR
81685,Sommore: Queen Chandelier,MOVIE,2023,69,comedy,US,6.100000,91.000000,1.960000,6.633194,Sommore,ACTOR
81687,All Na Vibes,MOVIE,2023,80,drama,NG,5.200000,18.000000,1.357000,4.000000,Adeola Layade Azaria,ACTOR
81703,Going to Heaven,MOVIE,2023,90,family,AE,7.000000,40.000000,19.267196,6.633194,Unknown,Unknown

In [143]:
#Scaling using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

In [144]:
scaler = MinMaxScaler()

In [145]:
numeric_cols = [
    'release_year',
    'runtime',
    'imdb_score',
    'imdb_votes',
    'tmdb_popularity',
    'tmdb_score'
]
df_work[numeric_cols] = scaler.fit_transform(df_work[numeric_cols])

In [146]:
df_work

,title,type,release_year,runtime,main_genre,lead_production_country,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role
0,Five Came Back: The Reference Films,SHOW,0.000000,0.226667,documentation,US,0.622339,0.007877,0.000548,0.645599,Unknown,Unknown
1,Rocky,MOVIE,0.397436,0.528889,drama,US,0.814815,0.219086,0.098599,0.766526,Sylvester Stallone,ACTOR
51,Grease,MOVIE,0.423077,0.488889,romance,US,0.703704,0.105543,0.030734,0.726947,John Travolta,ACTOR
99,The Sting,MOVIE,0.358974,0.573333,crime,US,0.839506,0.099367,0.022813,0.791579,Paul Newman,ACTOR
142,Rocky II,MOVIE,0.435897,0.528889,drama,US,0.716049,0.080580,0.070172,0.710105,Sylvester Stallone,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,MOVIE,1.000000,0.360000,family,KW,0.622339,0.007877,0.003098,0.157895,Bader Al Atwan,ACTOR
81655,Sweetie,MOVIE,1.000000,0.533333,documentation,TR,0.790123,0.000076,0.002263,0.705263,Yıldız Kenter,ACTOR
81685,Sommore: Queen Chandelier,MOVIE,1.000000,0.306667,comedy,US,0.567901,0.000032,0.001808,0.645599,Sommore,ACTOR
81687,All Na Vibes,MOVIE,1.000000,0.355556,drama,NG,0.456790,0.000005,0.001249,0.368421,Adeola Layade Azaria,ACTOR
81703,Going to Heaven,MOVIE,1.000000,0.400000,family,AE,0.679012,0.000013,0.017854,0.645599,Unknown,Unknown

In [147]:
#One hot encoding 
df_work = pd.get_dummies(
    df_work,
    columns=['type', 'main_genre', 'lead_production_country'],
    drop_first=True,dtype=int
)

In [149]:
df_work

,title,release_year,runtime,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,name,role,type_SHOW,...,lead_production_country_TN,lead_production_country_TR,lead_production_country_TW,lead_production_country_TZ,lead_production_country_UA,lead_production_country_US,lead_production_country_UY,lead_production_country_VN,lead_production_country_ZA,lead_production_country_ZW
0,Five Came Back: The Reference Films,0.000000,0.226667,0.622339,0.007877,0.000548,0.645599,Unknown,Unknown,1,...,0,0,0,0,0,1,0,0,0,0
1,Rocky,0.397436,0.528889,0.814815,0.219086,0.098599,0.766526,Sylvester Stallone,ACTOR,0,...,0,0,0,0,0,1,0,0,0,0
51,Grease,0.423077,0.488889,0.703704,0.105543,0.030734,0.726947,John Travolta,ACTOR,0,...,0,0,0,0,0,1,0,0,0,0
99,The Sting,0.358974,0.573333,0.839506,0.099367,0.022813,0.791579,Paul Newman,ACTOR,0,...,0,0,0,0,0,1,0,0,0,0
142,Rocky II,0.435897,0.528889,0.716049,0.080580,0.070172,0.710105,Sylvester Stallone,ACTOR,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,1.000000,0.360000,0.622339,0.007877,0.003098,0.157895,Bader Al Atwan,ACTOR,0,...,0,0,0,0,0,0,0,0,0,0
81655,Sweetie,1.000000,0.533333,0.790123,0.000076,0.002263,0.705263,Yıldız Kenter,ACTOR,0,...,0,1,0,0,0,0,0,0,0,0
81685,Sommore: Queen Chandelier,1.000000,0.306667,0.567901,0.000032,0.001808,0.645599,Sommore,ACTOR,0,...,0,0,0,0,0,1,0,0,0,0
81687,All Na Vibes,1.000000,0.355556,0.456790,0.000005,0.001249,0.368421,Adeola Layade Azaria,ACTOR,0,...,0,0,0,0,0,0,0,0,0,0
81703,Going to Heaven,1.000000,0.400000,0.679012,0.000013,0.017854,0.645599,Unknown,Unknown,0,...,0,0,0,0,0,0,0,0,0,0

In [150]:
#Dropping name and role
df_work.drop(columns=['name', 'role'], inplace=True)

In [151]:
df_work

,title,release_year,runtime,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,type_SHOW,main_genre_animation,main_genre_comedy,...,lead_production_country_TN,lead_production_country_TR,lead_production_country_TW,lead_production_country_TZ,lead_production_country_UA,lead_production_country_US,lead_production_country_UY,lead_production_country_VN,lead_production_country_ZA,lead_production_country_ZW
0,Five Came Back: The Reference Films,0.000000,0.226667,0.622339,0.007877,0.000548,0.645599,1,0,0,...,0,0,0,0,0,1,0,0,0,0
1,Rocky,0.397436,0.528889,0.814815,0.219086,0.098599,0.766526,0,0,0,...,0,0,0,0,0,1,0,0,0,0
51,Grease,0.423077,0.488889,0.703704,0.105543,0.030734,0.726947,0,0,0,...,0,0,0,0,0,1,0,0,0,0
99,The Sting,0.358974,0.573333,0.839506,0.099367,0.022813,0.791579,0,0,0,...,0,0,0,0,0,1,0,0,0,0
142,Rocky II,0.435897,0.528889,0.716049,0.080580,0.070172,0.710105,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,1.000000,0.360000,0.622339,0.007877,0.003098,0.157895,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81655,Sweetie,1.000000,0.533333,0.790123,0.000076,0.002263,0.705263,0,0,0,...,0,1,0,0,0,0,0,0,0,0
81685,Sommore: Queen Chandelier,1.000000,0.306667,0.567901,0.000032,0.001808,0.645599,0,0,1,...,0,0,0,0,0,1,0,0,0,0
81687,All Na Vibes,1.000000,0.355556,0.456790,0.000005,0.001249,0.368421,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81703,Going to Heaven,1.000000,0.400000,0.679012,0.000013,0.017854,0.645599,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [152]:
df_work.columns

Index(['title', 'release_year', 'runtime', 'imdb_score', 'imdb_votes',
       'tmdb_popularity', 'tmdb_score', 'type_SHOW', 'main_genre_animation',
       'main_genre_comedy',
       ...
       'lead_production_country_TN', 'lead_production_country_TR',
       'lead_production_country_TW', 'lead_production_country_TZ',
       'lead_production_country_UA', 'lead_production_country_US',
       'lead_production_country_UY', 'lead_production_country_VN',
       'lead_production_country_ZA', 'lead_production_country_ZW'],
      dtype='object', length=117)

In [153]:
df_work.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6137 entries, 0 to 81703
Columns: 117 entries, title to lead_production_country_ZW
dtypes: float64(6), int64(110), object(1)
memory usage: 5.5+ MB

In [155]:
#Separate title from the feature matrix
titles = df_work['title']
titles

0        Five Came Back: The Reference Films
1                                      Rocky
51                                    Grease
99                                 The Sting
142                                 Rocky II
                        ...
81649                          عبود في البيت
81655                                Sweetie
81685              Sommore: Queen Chandelier
81687                           All Na Vibes
81703                        Going to Heaven
Name: title, Length: 6137, dtype: object

In [157]:
X = df_work.drop(columns=['title'])
X

,release_year,runtime,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,type_SHOW,main_genre_animation,main_genre_comedy,main_genre_crime,...,lead_production_country_TN,lead_production_country_TR,lead_production_country_TW,lead_production_country_TZ,lead_production_country_UA,lead_production_country_US,lead_production_country_UY,lead_production_country_VN,lead_production_country_ZA,lead_production_country_ZW
0,0.000000,0.226667,0.622339,0.007877,0.000548,0.645599,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0.397436,0.528889,0.814815,0.219086,0.098599,0.766526,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
51,0.423077,0.488889,0.703704,0.105543,0.030734,0.726947,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
99,0.358974,0.573333,0.839506,0.099367,0.022813,0.791579,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
142,0.435897,0.528889,0.716049,0.080580,0.070172,0.710105,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81649,1.000000,0.360000,0.622339,0.007877,0.003098,0.157895,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81655,1.000000,0.533333,0.790123,0.000076,0.002263,0.705263,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
81685,1.000000,0.306667,0.567901,0.000032,0.001808,0.645599,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
81687,1.000000,0.355556,0.456790,0.000005,0.001249,0.368421,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81703,1.000000,0.400000,0.679012,0.000013,0.017854,0.645599,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

DBSCAN

In [165]:
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_samples, silhouette_score
eps_array = [0.2, 0.5, 1]
min_samples_array = [5, 10, 30]

for eps in eps_array: 
    for min_sample in min_samples_array:
        cluster = DBSCAN(eps=eps, min_samples=min_sample)
        cluster_labels = cluster.fit_predict(X)

        #Skip  if only one cluster or all noise
        if len(set(cluster_labels)) <=1 or len(set(cluster_labels)) == {-1}:
            continue
        silhouette_avg = silhouette_score(X, cluster_labels)
    
        print(f"eps = {eps}, min_samples = {min_sample}")
        print(f"Number of clusters: {len(set(cluster_labels)) - (1 if -1 in cluster_labels else 0)}")
        print(f"Silhouette Score: {silhouette_avg:.3f}\n")

eps = 0.2, min_samples = 5
Number of clusters: 174
Silhouette Score: 0.462

eps = 0.2, min_samples = 10
Number of clusters: 95
Silhouette Score: 0.333

eps = 0.2, min_samples = 30
Number of clusters: 23
Silhouette Score: 0.091

eps = 0.5, min_samples = 5
Number of clusters: 211
Silhouette Score: 0.570

eps = 0.5, min_samples = 10
Number of clusters: 120
Silhouette Score: 0.462

eps = 0.5, min_samples = 30
Number of clusters: 36
Silhouette Score: 0.203

eps = 1, min_samples = 5
Number of clusters: 214
Silhouette Score: 0.575

eps = 1, min_samples = 10
Number of clusters: 121
Silhouette Score: 0.465

eps = 1, min_samples = 30
Number of clusters: 38
Silhouette Score: 0.215

In [166]:
dbscan_model = DBSCAN(eps=1, min_samples=5)

In [167]:
dbscan_model.fit(X)

DBSCAN(eps=1)

In [169]:

print("Cluster ", len(set(dbscan_model.labels_)))
print("Score: ", silhouette_score(X, dbscan_model.labels_))

Cluster  215
Score:  0.5745572380134207

In [170]:
df_work['dbscan_cluster'] = dbscan_model.labels_

In [171]:
df_work['dbscan_cluster']

0         0
1         1
51        2
99        3
142       1
         ..
81649    -1
81655    -1
81685     4
81687    80
81703    -1
Name: dbscan_cluster, Length: 6137, dtype: int64

In [173]:
dbscan_model.labels_

array([ 0,  1,  2, ...,  4, 80, -1], shape=(6137,))

In [174]:
df_work

,title,release_year,runtime,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,type_SHOW,main_genre_animation,main_genre_comedy,...,lead_production_country_TR,lead_production_country_TW,lead_production_country_TZ,lead_production_country_UA,lead_production_country_US,lead_production_country_UY,lead_production_country_VN,lead_production_country_ZA,lead_production_country_ZW,dbscan_cluster
0,Five Came Back: The Reference Films,0.000000,0.226667,0.622339,0.007877,0.000548,0.645599,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1,Rocky,0.397436,0.528889,0.814815,0.219086,0.098599,0.766526,0,0,0,...,0,0,0,0,1,0,0,0,0,1
51,Grease,0.423077,0.488889,0.703704,0.105543,0.030734,0.726947,0,0,0,...,0,0,0,0,1,0,0,0,0,2
99,The Sting,0.358974,0.573333,0.839506,0.099367,0.022813,0.791579,0,0,0,...,0,0,0,0,1,0,0,0,0,3
142,Rocky II,0.435897,0.528889,0.716049,0.080580,0.070172,0.710105,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,1.000000,0.360000,0.622339,0.007877,0.003098,0.157895,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
81655,Sweetie,1.000000,0.533333,0.790123,0.000076,0.002263,0.705263,0,0,0,...,1,0,0,0,0,0,0,0,0,-1
81685,Sommore: Queen Chandelier,1.000000,0.306667,0.567901,0.000032,0.001808,0.645599,0,0,1,...,0,0,0,0,1,0,0,0,0,4
81687,All Na Vibes,1.000000,0.355556,0.456790,0.000005,0.001249,0.368421,0,0,0,...,0,0,0,0,0,0,0,0,0,80
81703,Going to Heaven,1.000000,0.400000,0.679012,0.000013,0.017854,0.645599,0,0,0,...,0,0,0,0,0,0,0,0,0,-1

Movie Recomendation Funciton

In [188]:
import random

def recommend_movie(movie_name: str, n=5):
    movie_name = movie_name.lower()
    
    # match against the 'title' column (not index)
    matches = df_work[df_work['title'].str.lower().str.contains(movie_name, na=False)]
    
    if matches.empty:
        print('Movie not found in the database.')
        return []
    
    if len(matches) > 1:
        print(f"Multiple matches found, using: '{matches.iloc[0]['title']}'")
    
    movie = matches.iloc[0]
    cluster = movie['dbscan_cluster']
    
    if cluster == -1:
        print(f"'{movie['title']}' is an outlier — no similar cluster found.")
        return []
    
    cluster_movies = df_work[
        (df_work['dbscan_cluster'] == cluster) & (df_work['title'] != movie['title'])
    ]
    
    if cluster_movies.empty:
        print(f"No other movies found in the same cluster as '{movie['title']}'.")
        return []
    
    n = min(n, len(cluster_movies))
    recommended_titles = random.sample(list(cluster_movies['title']), n)
    
    print('--- We can recommend you these movies ---')
    for m in recommended_titles:
        print(m)
    
    return recommended_titles

In [193]:
input_movie = input("Enter the movie")
recommend_movie(input_movie)

Enter the movie Going to Heaven

'Going to Heaven' is an outlier — no similar cluster found.

[]

In [191]:
df_work

,title,release_year,runtime,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,type_SHOW,main_genre_animation,main_genre_comedy,...,lead_production_country_TR,lead_production_country_TW,lead_production_country_TZ,lead_production_country_UA,lead_production_country_US,lead_production_country_UY,lead_production_country_VN,lead_production_country_ZA,lead_production_country_ZW,dbscan_cluster
0,Five Came Back: The Reference Films,0.000000,0.226667,0.622339,0.007877,0.000548,0.645599,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1,Rocky,0.397436,0.528889,0.814815,0.219086,0.098599,0.766526,0,0,0,...,0,0,0,0,1,0,0,0,0,1
51,Grease,0.423077,0.488889,0.703704,0.105543,0.030734,0.726947,0,0,0,...,0,0,0,0,1,0,0,0,0,2
99,The Sting,0.358974,0.573333,0.839506,0.099367,0.022813,0.791579,0,0,0,...,0,0,0,0,1,0,0,0,0,3
142,Rocky II,0.435897,0.528889,0.716049,0.080580,0.070172,0.710105,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81649,عبود في البيت,1.000000,0.360000,0.622339,0.007877,0.003098,0.157895,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
81655,Sweetie,1.000000,0.533333,0.790123,0.000076,0.002263,0.705263,0,0,0,...,1,0,0,0,0,0,0,0,0,-1
81685,Sommore: Queen Chandelier,1.000000,0.306667,0.567901,0.000032,0.001808,0.645599,0,0,1,...,0,0,0,0,1,0,0,0,0,4
81687,All Na Vibes,1.000000,0.355556,0.456790,0.000005,0.001249,0.368421,0,0,0,...,0,0,0,0,0,0,0,0,0,80
81703,Going to Heaven,1.000000,0.400000,0.679012,0.000013,0.017854,0.645599,0,0,0,...,0,0,0,0,0,0,0,0,0,-1

After training our DBSCAN model, save the model (and scaler, if you used one) so FastAPI can load it without retraining.

In [194]:
import joblib

joblib.dump(dbscan_model, "dbscan_model.pkl")
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(X.columns.to_list(), )

NameError: name 'joblb' is not defined